version: 4.2.5

base_info:
  primary_color: "#24c6dc"
  title: Reln 的小窝
  author: Reln Ding
  avatar: /images/avatar.svg
  logo: /images/logo.svg
  favicon: /favicon.ico

# 顶部导航
nav_more_list:
  - name: GitHub
    url: https://github.com/lcha-reln
    icon: fab fa-github

# 页面顶部菜单
menu:
  home: / || fas fa-home
  archives: /archives || fas fa-archive
  tags: /tags || fas fa-tags
  categories: /categories || fas fa-th

# 代码高亮
code_block:
  copy: true
  lang: true
  highlight_theme: default

# 文章
post:
  author_badge:
    enable: false
  toc:
    enable: true
    number: true
  copyright:
    enable: false

# 页脚
footer:
  since: 2026
  icon: fas fa-heart
  powered:
    enable: true

# 评论（关闭）
comment:
  enable: false
